# Generated by Django 4.2.3 on 2023-12-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_alter_receipe_receipe_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receipe',
            new_name='abcd',
        ),
    ]
