# Generated by Django 4.2.3 on 2023-12-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0003_rename_receipe_abcd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abcd',
            new_name='receipe',
        ),
    ]
